// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmfflpteebrclnkifqqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZmZscHRlZWJyY2xua2lmcXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzAzMzMsImV4cCI6MjA3MDk0NjMzM30.3PPHAMDrm_u0SjQGV-noOTWR3Bu7XE0OMkTm1nEZFkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});